# Generated by Django 5.0.2 on 2025-09-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_invitationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='role',
            field=models.CharField(choices=[('full', 'Full User'), ('memory', 'Memory User')], default='full', max_length=10),
        ),
    ]
