# Generated by Django 5.0.2 on 2025-09-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_invitationcode_role'),
    ]

    operations = [
        # Remove old fields
        migrations.RemoveField(
            model_name='invitationcode',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='used_by',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='used_at',
        ),
        # Add new fields
        migrations.AddField(
            model_name='invitationcode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this code can be used for new registrations'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Number of times this code has been used'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
