# Generated by Django 5.0.2 on 2025-09-13 15:07

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.get_thumbnail_upload_path),
        ),
    ]
