# Generated by Django 5.0.2 on 2025-09-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_person_facetag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='FaceTag',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
