# Generated by Django 5.0.2 on 2025-09-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_alter_person_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStyleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_theme', models.CharField(choices=[('default', 'Default'), ('verona_sunset', 'Verona Sunset')], default='default', help_text='Select the visual theme for the wedding gallery', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this styling configuration is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Style Configuration',
                'verbose_name_plural': 'Site Style Configurations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
