# Generated by Django 5.0.2 on 2025-10-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_sitestyleconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteStyleConfiguration',
        ),
        migrations.AddField(
            model_name='image',
            name='face_height',
            field=models.FloatField(blank=True, help_text='Face height (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='face_width',
            field=models.FloatField(blank=True, help_text='Face width (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='face_x',
            field=models.FloatField(blank=True, help_text='Face center X coordinate (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='face_y',
            field=models.FloatField(blank=True, help_text='Face center Y coordinate (0-1)', null=True),
        ),
    ]
