# Generated by Django 5.0.2 on 2025-10-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_emailverificationtoken_passwordresettoken'),
    ]

    operations = [
    ]
