# Generated by Django 5.0.2 on 2025-10-08 21:49

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_auto_20251004_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='vimeo_url',
            field=models.URLField(blank=True, help_text='Vimeo embed URL with domain-level privacy', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.get_image_upload_path),
        ),
    ]
