# Generated by Django 5.0.2 on 2025-10-09 15:26

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_image_vimeo_url_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image for videos', null=True, upload_to=images.models.get_image_upload_path),
        ),
    ]
