# Generated by Django 6.0.1 on 2026-03-27 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_image_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='token_prefix',
            field=models.CharField(db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='token_prefix',
            field=models.CharField(db_index=True, default='', max_length=16),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['image', 'created_at'], name='images_comm_image_i_bec79b_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-uploaded_at'], name='images_imag_uploade_ceef9a_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploader'], name='images_imag_uploade_45d228_idx'),
        ),
    ]
