# Generated by Django 5.0.2 on 2026-06-27 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_image_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Guest book entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemorableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(choices=[('wedding', 'Wedding Day'), ('proposal', 'Proposal'), ('honeymoon', 'Honeymoon'), ('custom', 'Custom')], max_length=20)),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, help_text="Custom label (for 'custom' type)", max_length=100)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='flag_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='token_prefix',
            field=models.CharField(db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='image',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, help_text='Original image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Original image width in pixels', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='token_prefix',
            field=models.CharField(db_index=True, default='', max_length=16),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['image', 'created_at'], name='images_comm_image_i_bec79b_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-uploaded_at'], name='images_imag_uploade_ceef9a_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploader'], name='images_imag_uploade_45d228_idx'),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memorabledate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
