# Generated by Django 5.0.2 on 2026-06-27 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_guestbookentry_memorabledate_comment_flag_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_one_name', models.CharField(blank=True, default='', max_length=80)),
                ('partner_two_name', models.CharField(blank=True, default='', max_length=80)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, default='', max_length=160)),
                ('venue_url', models.URLField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', help_text='City, State/Region — shown next to the date in the masthead.', max_length=160)),
                ('intro_text', models.TextField(blank=True, default='', help_text='Italic subtitle under the names on the gallery masthead.')),
                ('featured_title', models.CharField(blank=True, default='', help_text='Caption shown over the featured photo. Leave blank for no text overlay.', max_length=120)),
                ('featured_subtitle', models.CharField(blank=True, default='', max_length=160)),
                ('site_domain', models.CharField(blank=True, default='', help_text='Shown in the footer, e.g. "yourwedding.com".', max_length=120)),
                ('footer_message', models.CharField(blank=True, default='With love, from our day to yours.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Large hero photo at the top of the gallery. Leave empty to use the most-liked photo automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.image')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
