# Generated by Django 5.0.2 on 2026-03-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_comment_flag_count_comment_flagged_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, help_text='Original image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Original image width in pixels', null=True),
        ),
    ]
