# Generated by Django 5.0.2 on 2026-06-29 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_image_image_height_image_image_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human label, e.g. "claude-labeler".', max_length=100)),
                ('key_prefix', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('key_hash', models.CharField(editable=False, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Guest book entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemorableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(choices=[('wedding', 'Wedding Day'), ('proposal', 'Proposal'), ('honeymoon', 'Honeymoon'), ('custom', 'Custom')], max_length=20)),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, help_text="Custom label (for 'custom' type)", max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_one_name', models.CharField(blank=True, default='', max_length=80)),
                ('partner_two_name', models.CharField(blank=True, default='', max_length=80)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, default='', max_length=160)),
                ('venue_url', models.URLField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', help_text='City, State/Region — shown next to the date in the masthead.', max_length=160)),
                ('intro_text', models.TextField(blank=True, default='', help_text='Italic subtitle under the names on the gallery masthead.')),
                ('featured_title', models.CharField(blank=True, default='', help_text='Caption shown over the featured photo. Leave blank for no text overlay.', max_length=120)),
                ('featured_subtitle', models.CharField(blank=True, default='', max_length=160)),
                ('site_domain', models.CharField(blank=True, default='', help_text='Shown in the footer, e.g. "yourwedding.com".', max_length=120)),
                ('footer_message', models.CharField(blank=True, default='With love, from our day to yours.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Large hero photo at the top of the gallery. Leave empty to use the most-liked photo automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.image')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='ImageLabelSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_title', models.CharField(blank=True, default='', max_length=255)),
                ('suggested_description', models.TextField(blank=True, default='')),
                ('suggested_tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(help_text='Producer, e.g. "claude-opus-4-8".', max_length=64)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, default='', help_text='Why the agent chose this label.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_suggestions', to='images.image')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['image', 'status'], name='images_imag_image_i_5364e5_idx')],
            },
        ),
    ]
