# Generated by Django 5.2.8 on 2026-06-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_agentapikey_guestbookentry_memorabledate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='labeling_context',
            field=models.TextField(blank=True, default='', help_text='Extra context for AI photo labeling — a description of the venue and setting, season, notable features, etc. Not shown publicly; fed to the model so captions can reference the location accurately.'),
        ),
    ]
