# Generated by Django 5.2.8 on 2026-06-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_siteconfiguration_labeling_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('person', 'Person'), ('scene', 'Scene'), ('other', 'Other')], default='other', help_text='Person tags name people in the photo; scene/other describe the setting.', max_length=10),
        ),
        migrations.AddField(
            model_name='tag',
            name='suggested',
            field=models.BooleanField(default=True, help_text='Offer this tag in autocomplete and allow AI labeling to use it. Uncheck to keep an incidental tag out of suggestions.'),
        ),
    ]
