# Generated by Django 5.2.8 on 2026-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0022_tag_kind_tag_suggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='caption_prompt',
            field=models.TextField(blank=True, default='', help_text='System prompt for AI caption generation. Leave blank to use the built-in default. Editable here or on the labeling dashboard.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='match_prompt',
            field=models.TextField(blank=True, default='', help_text='System prompt for AI people-matching. Leave blank to use the built-in default.'),
        ),
    ]
