# Generated by Django 5.2.8 on 2026-06-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0023_siteconfiguration_caption_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='randomize_featured',
            field=models.BooleanField(default=False, help_text='Show a random photo as the opening/featured frame on each visit (overrides the chosen featured photo above).'),
        ),
    ]
